---
- include_role:
    name: "corpusops.roles/vars"
  tags: [elasticsearch, vars, elasticsearch_vars]
# set the cops_elasticsearch_vars var from defaults/main.yml
- include_role: {name: corpusops.roles/vars_registry}
  vars:
    cops_vars_registry_target: cops_elasticsearch
  tags: [elasticsearch, vars, elasticsearch_vars]
- include_jinja_vars:
    name: __GLOBAL__
    content: |
      ---
      {% set prefix = 'cops_elasticsearch' %}
      {% set p = prefix + '_vars' %}
      {% set _vars = {p: vars[p]} %}
      #
      {% set env = _vars[p].env %}
      #
      {% set _ = env.update(_vars[p].env_overrides) %}
      #
      {% for i, val in vars.get('ansible_env', {}).items() %}
      {%  if not i.startswith(
              ('OLDPWD', 'CWD', 'PWD',
               'TERM', 'USER', 'HOME', 'PS1',
               'PATH', 'ANSIBLE', 'SSH', 'LS')) %}
      {%    set _ = env.update({i: val})%}
      {%  endif %}
      {% endfor %}
      #
      {% for n in ['nginx'] %}
      {%  set _n = _vars[p].setdefault(n, {}) %}
      {%  for i, val in _vars[p].items() %}
      {%    set pref = n+'_' %}
      {%    if i.startswith(pref) and i not in [pref] %}
      {%      set _ = _n.update({
                pref.join(i.split(pref)[1:]): val}) %}
      {%    endif %}
      {%  endfor %}
      {% endfor %}
      #
      {{ _vars | to_json }}
  tags: [elasticsearch, vars, elasticsearch_vars]
